apiVersion: v1
kind: Pod
metadata:
  name: nginx-web-server
  labels:
    app: nginx-web-server
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: "64Mi" # 64Mi is equivalent to 64 Mebibytes (MiB) ~ 67.1 MB (https://digilent.com/blog/mib-vs-mb-whats-the-difference/?srsltid=AfmBOoqmRcJEDVQQnKYWRhJ6TQYaDMrF2kLrDXeLcbt1p1hr2VEVgWkk)
          cpu: "250m" # 250m is equivalent to 0.25 CPU
        limits:
          memory: "128Mi"
          cpu: "500m"