apiVersion: v1
kind: Service
metadata:
  name: data-tier
  labels:
    app: micro
    tier: data
    env: dev
spec:
  ports:
  - port: 6379
    name: redis
    protocol: TCP
  selector:
    tier: data
    env: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-tier
  labels:
    app: micro
    tier: data
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: data
      env: dev
  template:
    metadata:
      labels:
        tier: data
        env: dev
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        livenessProbe:
          tcpSocket:
            port: redis
          initialDelaySeconds: 15
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
  
    