apiVersion: v1
kind: Service
metadata:
  name: app-tier-service
  labels:
    app: microservices
    env: dev
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    tier: app
    env: dev
---
apiVersion: v1
kind: Pod
metadata:
  name: app-tier-pod
  labels:
    tier: app
    env: dev
spec:
  containers:
    - name: server
      image: lrakai/microservices:server-v1
      ports:
        - containerPort: 80
      env:
        - name: REDIS_URL
          value: redis://$(DATA_TIER_SERVICE_SERVICE_HOST):$(DATA_TIER_SERVICE_SERVICE_PORT_REDIS)
  